### ISSUE TITLE
papers

### ISSUE THREAD

**Issue by necrose99** [wolfden/slwolf#1]
https://github.com/Sabayon-Labs/General-Sabayon-Linux-Artwork/blob/master/sabayon-japan-landscapes_00369612.png (open your source open your mind) 
あなたのソースを开いて、あなたの心を开きます
ｻﾊﾞﾖﾝ  (sabayon) の (no ='s or ( belongs to) ABC の News)

https://github.com/Sabayon-Labs/General-Sabayon-Linux-Artwork/blob/master/Sabayon-lotr-ring-glow-wallpaer.png (feeling Tolkien ? MS word LOTR macro writer for scripts )  
(and the sub parts used paint.net /mono paint) 

https://raw.githubusercontent.com/Sabayon-Labs/General-Sabayon-Linux-Artwork/master/Sabayon-Zoro-Wallpaers/Sabayon-Linux-Defender-Bushido.png  (mulder and crew beat me to the server , aspects, need to fork this and clean of the zoro/left footter )

**Comment by wolfden** [comment]
Thank you!

On Wed, May 13, 2015 at 9:04 AM, Michael R. Lawrence <
notifications@github.com> wrote:

> https://github.com/Sabayon-Labs/General-Sabayon-Linux-Artwork/blob/master/sabayon-japan-landscapes_00369612.png
> (open your source open your mind)
> あなたのソースを開いて、あなたの心を開きます
> ｻﾊﾞﾖﾝ (sabayon) の (no ='s or ( belongs to) ABC の News)
> 
> https://github.com/Sabayon-Labs/General-Sabayon-Linux-Artwork/blob/master/Sabayon-lotr-ring-glow-wallpaer.png
> (feeling Tolkien ? MS word LOTR macro writer for scripts )
> 
> (and the sub parts used paint.net /mono paint)
> 
> https://raw.githubusercontent.com/Sabayon-Labs/General-Sabayon-Linux-Artwork/master/Sabayon-Zoro-Wallpaers/Sabayon-Linux-Defender-Bushido.png
> (mulder and crew beat me to the server , aspects, need to fork this and
> clan of the zoro )
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wolfden/slwolf/issues/1.

## 

KJS
~wolfden~
